import { useState, useEffect, useRef } from 'react';
import { Moon, Sun, Languages, HelpCircle, Send, X, Menu, User, Sparkles } from 'lucide-react';

export default function App() {
  const [darkMode, setDarkMode] = useState(false);
  const [language, setLanguage] = useState('en');
  const [character, setCharacter] = useState('formal');
  const [message, setMessage] = useState('');
  const [showDisclaimer, setShowDisclaimer] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [messages, setMessages] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  function renderBold(text) {
    return text.replace(
      /\*\*\*(.+?)\*\*\*/g,
      '<span class="font-semibold text-blue-500">$1</span>'
    );
  }
  // Toggle dark mode and store preference
  const toggleDarkMode = () => {
    setDarkMode(!darkMode);
    localStorage.setItem('darkMode', !darkMode);
  };

  // Toggle language between English and Thai
  const toggleLanguage = () => {
    const newLanguage = language === 'en' ? 'th' : 'en';
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  // Toggle character between Formal and Indie
  const toggleCharacter = () => {
    const newCharacter = character === 'formal' ? 'indie' : 'formal';
    setCharacter(newCharacter);
    localStorage.setItem('character', newCharacter);
  };

  // Load preferences from localStorage on component mount
  useEffect(() => {
    const savedDarkMode = localStorage.getItem('darkMode') === 'true';
    const savedLanguage = localStorage.getItem('language') || 'en';
    const savedCharacter = localStorage.getItem('character') || 'formal';
    setDarkMode(savedDarkMode);
    setLanguage(savedLanguage);
    setCharacter(savedCharacter);
  }, []);

  // Send a message
  const handleSendMessage = async (e) => {
    e.preventDefault();
    if (!message.trim()) return;
  
    const newMessages = [...messages, { role: 'user', content: message }];
    setMessages(newMessages);
    setIsLoading(true);
  
    try {
      const response = await fetch('http://localhost:5000/api/analyze', {   // <<== URL ไปยัง backend API
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ 
          prompt: message, 
          language: language,
          character: character
        }),
      });
  
      const data = await response.json();
  
      setMessages([
        ...newMessages,
        { role: 'assistant', content: data.answer }  // <<== ใช้คำตอบจาก backend
      ]);
      setMessage('');
    } catch (error) {
      console.error('Error contacting backend:', error);
      setMessages([
        ...newMessages,
        { role: 'assistant', content: 'An error occurred. Please try again later.' }
      ]);
    } finally {
      setIsLoading(false);
      setMessage('');
    }
  };

  const chatContainerRef = useRef(null);

    useEffect(() => {
      if (chatContainerRef.current) {
        chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
      }
    }, [messages, isLoading]);
  
  // Translations
  const translations = {
    en: {
      placeholder: "Describe your dream here...",
      send: "Send",
      disclaimer: "**Disclaimer:** DreamSense provides dream interpretations generated by AI for informational and entertainment purposes only. Interpretations should not be considered as medical, psychological, or professional advice. Always trust your own feelings and consult a professional if needed.",
      welcome: "Welcome to DreamSense AI✨",
      intro: "Share your dream, and I'll help you understand its meaning",
      analyzing: "Analyzing your dream...",
      formal: "Formal",
      indie: "Relax"
    },
    th: {
      placeholder: "อธิบายความฝันของคุณที่นี่...",
      send: "ส่ง",
      disclaimer: "**ข้อจำกัดความรับผิดชอบ:** DreamSense เป็นบริการวิเคราะห์ความฝันที่สร้างขึ้นโดย AI เพื่อวัตถุประสงค์ในการให้ข้อมูลและความบันเทิงเท่านั้น การตีความไม่ควรนำไปใช้แทนคำแนะนำทางการแพทย์ จิตวิทยา หรือคำแนะนำจากผู้เชี่ยวชาญ โปรดใช้วิจารณญาณและขอคำปรึกษาจากผู้เชี่ยวชาญหากจำเป็น",
      welcome: "ยินดีต้อนรับสู่ DreamSense AI✨",
      intro: "แบ่งปันความฝันของคุณ และเราจะช่วยคุณเข้าใจความหมายของมัน",
      analyzing: "กำลังวิเคราะห์ความฝันของคุณ...",
      formal: "ทางการ",
      indie: "ชิล"
    }
  };

  return (
    <>
    {/* preload both backgrounds */}
      <img src="/background-dreamsdark.webp" alt="" hidden />
      <img src="/background-dreamslight.webp" alt="" hidden />
    <div className={`flex flex-col h-screen transition-colors duration-[1000ms] ease-in-out overflow-hidden ${darkMode ? 'bg-slate-900 text-gray-100' : 'bg-sky-50 text-gray-800'}`}>
      {/* Main background image */}
      <div 
        className="fixed inset-0 w-full h-full bg-cover bg-center z-0" 
        style={{ 
          backgroundImage: `url(${darkMode ? '/background-dreamsdark.webp' : '/background-dreamslight.webp'})`,
          opacity: darkMode ? 0.4 : 0.8
        }}
      ></div>

      {/* Navbar */}
      <nav className={`relative z-10 px-4 py-5 flex justify-between items-center shadow-md ${darkMode ? 'bg-slate-950 bg-opacity-60' : 'bg-white bg-opacity-50'}`}>
        {/* Logo - Changed to switch between logos based on darkMode */}
        <div className="flex items-center">
          <img 
            src={darkMode ? "/DreamSense1.webp" : "/DreamSense2.webp"} 
            alt="DreamSense Logo" 
            className="h-8 md:h-8" // Adjusted height to fit properly
          />
        </div>
        
        {/* Mobile menu button */}
        <button 
          className="md:hidden p-2 rounded-md"
          onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
        >
          <Menu className={darkMode ? 'text-gray-200' : 'text-gray-700'} size={24} />
        </button>
        
        {/* Desktop Nav links */}
        <div className="hidden md:flex items-center space-x-4">
          {/* Character toggle button */}
          <button 
            onClick={toggleCharacter}
            className={`p-2 rounded-full transition-colors flex items-center ${darkMode ? 'bg-slate-700 text-white hover:bg-slate-600' : 'bg-sky-100 text-blue-800 hover:bg-sky-200'}`}
            aria-label={character === 'formal' ? 'Switch to indie character' : 'Switch to formal character'}
          >
            {character === 'formal' ? <User size={20} /> : <Sparkles size={20} />}
            <span className="ml-1 text-sm font-medium">{translations[language][character]}</span>
          </button>

          <button 
            onClick={toggleDarkMode}
            className={`p-2 rounded-full transition-colors ${darkMode ? 'bg-slate-700 text-white hover:bg-slate-600' : 'bg-sky-100 text-blue-800 hover:bg-sky-200'}`}
            aria-label={darkMode ? 'Switch to light mode' : 'Switch to dark mode'}
          >
            {darkMode ? <Sun size={20} /> : <Moon size={20} />}
          </button>
          
          {/* Fixed language button to have icon and text in horizontal alignment */}
          <button 
            onClick={toggleLanguage}
            className={`p-2 rounded-full transition-colors flex items-center ${darkMode ? 'bg-slate-700 text-white hover:bg-slate-600' : 'bg-sky-100 text-blue-800 hover:bg-sky-200'}`}
            aria-label={language === 'en' ? 'Switch to Thai language' : 'Switch to English language'}
          >
            <Languages size={20} />
            <span className="ml-1 text-sm font-medium">{language === 'en' ? 'TH' : 'EN'}</span>
          </button>
          
          <button 
            onClick={() => setShowDisclaimer(true)}
            className={`p-2 rounded-full transition-colors ${darkMode ? 'bg-slate-700 text-white hover:bg-slate-600' : 'bg-sky-100 text-blue-800 hover:bg-sky-200'}`}
            aria-label="Show disclaimer"
          >
            <HelpCircle size={20} />
          </button>
        </div>
      </nav>
      
      {/* Mobile menu */}
      {isMobileMenuOpen && (
        <div className={`md:hidden absolute top-16 right-0 z-20 w-48 py-2 shadow-lg rounded-bl-lg ${darkMode ? 'bg-slate-800 bg-opacity-95' : 'bg-white bg-opacity-95'}`}>
          {/* Character toggle button for mobile */}
          <button 
            onClick={toggleCharacter}
            className={`flex items-center w-full px-4 py-2 ${darkMode ? 'hover:bg-slate-700' : 'hover:bg-sky-50'}`}
          >
            {character === 'formal' ? <User size={18} className="mr-2" /> : <Sparkles size={18} className="mr-2" />}
            {character === 'formal' ? translations[language].indie : translations[language].formal}
          </button>

          <button 
            onClick={toggleDarkMode}
            className={`flex items-center w-full px-4 py-2 ${darkMode ? 'hover:bg-slate-700' : 'hover:bg-sky-50'}`}
          >
            {darkMode ? <Sun size={18} className="mr-2 text-white" /> : <Moon size={18} className="mr-2 text-blue-800" />}
            {darkMode ? 'Light Mode' : 'Dark Mode'}
          </button>
          
          <button 
            onClick={toggleLanguage}
            className={`flex items-center w-full px-4 py-2 ${darkMode ? 'hover:bg-slate-700' : 'hover:bg-sky-50'}`}
          >
            <Languages size={18} className="mr-2" />
            {language === 'en' ? 'ภาษาไทย' : 'English'}
          </button>
          
          <button 
            onClick={() => {
              setShowDisclaimer(true);
              setIsMobileMenuOpen(false);
            }}
            className={`flex items-center w-full px-4 py-2 ${darkMode ? 'hover:bg-slate-700' : 'hover:bg-sky-50'}`}
          >
            <HelpCircle size={18} className="mr-2" />
            Disclaimer
          </button>
        </div>
      )}
      {/* Focus Spotlight */}
      <div className="fixed inset-0 z-5 pointer-events-none">
        <div
          className={`w-full h-full backdrop-blur-sm mask-radial transition-opacity duration-700 ease-in-out ${
            darkMode
              ? 'bg-black/60' // Dark Mode: เข้มขึ้น
              : 'bg-black/10' // Light Mode: เบาๆ ฟุ้งๆ
          }`}
        />
      </div>
      {/* Main app structure - Modified to create a fixed layout */}
      <div className="flex flex-col flex-1 relative z-10 overflow-hidden">
        {/* Chat container - Made scrollable */}
        <div className="flex-1 overflow-y-auto scroll-smooth" ref={chatContainerRef}>
          <div className="max-w-4xl mx-auto w-full p-4 space-y-4">
            {messages.length === 0 ? (
              <div className={`text-center py-12 ${darkMode ? 'text-gray-300' : 'text-gray-700'}`}>
                <div className="flex justify-center mb-6">
                  <div className={`p-6 rounded-full ${darkMode ? 'bg-blue-900 bg-opacity-50' : 'bg-blue-100 bg-opacity-70'}`}>
                    <Moon size={48} className={darkMode ? 'text-white' : 'text-blue-800'} />
                  </div>
                </div>
                <h2 className="text-2xl font-bold mb-3">{translations[language].welcome}</h2>
                <p className="text-lg">{translations[language].intro}</p>
              </div>
            ) : (
              messages.map((msg, index) => (
                <div 
                  key={index} 
                  className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
                >
                  <div 
                    className={`max-w-[80%] rounded-3xl px-4 py-3 ${
                      msg.role === 'user' 
                        ? darkMode 
                          ? 'bg-sky-700 text-white' 
                          : 'bg-sky-800 text-white' 
                        : darkMode 
                          ? 'bg-slate-800 text-gray-200 border border-slate-700' 
                          : 'bg-white text-gray-800 shadow-lg'
                    }`}
                  >
                    {msg.role === 'user' ? (
                    // ฝั่ง user ใช้ปกติ
                    msg.content.split('\n').map((line, idx) => (
                      <p key={idx} className="mb-2 whitespace-pre-wrap">{line}</p>
                    ))
                  ) : (
                    // ฝั่ง assistant ใช้ dangerouslySetInnerHTML + renderBold
                    <div
                      className="whitespace-pre-wrap leading-relaxed"
                      dangerouslySetInnerHTML={{ __html: renderBold(msg.content) }}
                    />
                  )}
                  </div>
                </div>
              ))
            )}
            
            {/* Loading indicator with animated clouds */}
            {isLoading && (
              <div className="relative z-10 flex justify-start pl-4 pt-3">
                <div className="relative w-[130px] h-[80px]">
                  <svg viewBox="0 0 130 80" className="w-full h-full">
                    <path
                      d="M30,60 
                        Q10,60 20,40 
                        Q10,20 35,25 
                        Q50,0 70,20 
                        Q90,10 95,30 
                        Q120,30 110,55 
                        Q110,70 90,65 
                        Q70,80 60,65 
                        Q40,80 30,60Z"
                      fill="white"
                      stroke="#d1d5db"
                      strokeWidth="2"
                    />
                  </svg>
                  {/* Dots */}
                  <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
                    <span className="dots text-gray-500 text-2xl font-bold tracking-widest animate-dots"></span>
                  </div>
                </div>
              </div>
            )}

          </div>
        </div>
        
        {/* Message input - Made transparent background */}
        <div className="sticky bottom-0 p-4 z-10">
          <div className="max-w-4xl mx-auto">
            <form onSubmit={handleSendMessage} className="relative">
              <input
                type="text"
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && !e.shiftKey) {
                    e.preventDefault(); // prevents newline
                    setMessage('');     // clear immediately
                    handleSendMessage(e); // call send function
                  }
                }}
                placeholder={translations[language].placeholder}
                className={`w-full p-4 pr-12 rounded-full border shadow-sm backdrop-blur-sm ${
                  darkMode 
                    ? 'bg-slate-800 bg-opacity-50 border-slate-700 text-white placeholder-gray-400' 
                    : 'bg-white bg-opacity-60 border-gray-300 text-gray-800 placeholder-gray-500'
                } focus:outline-none focus:ring-2 ${darkMode ? 'focus:ring-blue-500' : 'focus:ring-blue-400'}`}
              />
              <button 
                type="submit"
                className={`absolute right-2 top-1/2 transform -translate-y-1/2 p-2 rounded-full transition-colors ${
                  message.trim() 
                    ? darkMode 
                      ? 'bg-yellow-500 text-gray-900 hover:bg-yellow-400' 
                      : 'bg-blue-600 text-white hover:bg-blue-500' 
                    : darkMode 
                      ? 'bg-slate-700 text-gray-500 cursor-not-allowed' 
                      : 'bg-gray-200 text-gray-400 cursor-not-allowed'
                }`}
                disabled={!message.trim()}
                aria-label="Send message"
              >
                <Send size={20} />
              </button>
            </form>
          </div>
        </div>
      </div>
      
      {/* Disclaimer modal */}
      {showDisclaimer && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className={`relative max-w-md w-full rounded-lg p-6 ${darkMode ? 'bg-slate-800' : 'bg-white'} shadow-xl`}>
            <button 
              onClick={() => setShowDisclaimer(false)}
              className={`absolute top-2 right-2 p-1 rounded-full hover:bg-opacity-10 ${darkMode ? 'hover:bg-gray-200' : 'hover:bg-gray-800'}`}
              aria-label="Close disclaimer"
            >
              <X size={24} />
            </button>
            <h3 className="text-xl font-bold mb-4">{language === 'en' ? 'Disclaimer' : 'ข้อจำกัดความรับผิดชอบ'}</h3>
            <p className="whitespace-pre-line">{translations[language].disclaimer}</p>
          </div>
        </div>
      )}
      
      {/* Cloud animations and other styles */}
      <style jsx>{`
        @keyframes dotTyping {
          0%   { content: "•"; }
          25%  { content: "••"; }
          50%  { content: "•••"; }
          75%  { content: ""; }
          100% { content: ""; }
        }

        .dots::after {
          content: "";
           animation: dotTyping 1.5s infinite steps(4);
        }

          .overflow-y-auto {
          overflow-y: auto;
        }
          .scroll-smooth {
          scroll-behavior: smooth;
        }
        .mask-radial {
          -webkit-mask-image: radial-gradient(circle at center, transparent 30%, black 80%);
          mask-image: radial-gradient(circle at center, transparent 30%, black 80%);
        }

      `}</style>
    </div>
    </>
  );
}